# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucasmull/Trabalho/libpq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucasmull/Trabalho/libpq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucasmull/Trabalho/libpq/CMakeFiles /home/lucasmull/Trabalho/libpq/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucasmull/Trabalho/libpq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testlibpq3.exe

# Build rule for target.
testlibpq3.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testlibpq3.exe
.PHONY : testlibpq3.exe

# fast build rule for target.
testlibpq3.exe/fast:
	$(MAKE) -f CMakeFiles/testlibpq3.exe.dir/build.make CMakeFiles/testlibpq3.exe.dir/build
.PHONY : testlibpq3.exe/fast

#=============================================================================
# Target rules for targets named testlibpq2.exe

# Build rule for target.
testlibpq2.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testlibpq2.exe
.PHONY : testlibpq2.exe

# fast build rule for target.
testlibpq2.exe/fast:
	$(MAKE) -f CMakeFiles/testlibpq2.exe.dir/build.make CMakeFiles/testlibpq2.exe.dir/build
.PHONY : testlibpq2.exe/fast

#=============================================================================
# Target rules for targets named testlibpq.exe

# Build rule for target.
testlibpq.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testlibpq.exe
.PHONY : testlibpq.exe

# fast build rule for target.
testlibpq.exe/fast:
	$(MAKE) -f CMakeFiles/testlibpq.exe.dir/build.make CMakeFiles/testlibpq.exe.dir/build
.PHONY : testlibpq.exe/fast

#=============================================================================
# Target rules for targets named test.exe

# Build rule for target.
test.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test.exe
.PHONY : test.exe

# fast build rule for target.
test.exe/fast:
	$(MAKE) -f CMakeFiles/test.exe.dir/build.make CMakeFiles/test.exe.dir/build
.PHONY : test.exe/fast

#=============================================================================
# Target rules for targets named pq

# Build rule for target.
pq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pq
.PHONY : pq

# fast build rule for target.
pq/fast:
	$(MAKE) -f libpq/CMakeFiles/pq.dir/build.make libpq/CMakeFiles/pq.dir/build
.PHONY : pq/fast

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/test.exe.dir/build.make CMakeFiles/test.exe.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/test.exe.dir/build.make CMakeFiles/test.exe.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/test.exe.dir/build.make CMakeFiles/test.exe.dir/test.c.s
.PHONY : test.c.s

testlibpq.o: testlibpq.c.o

.PHONY : testlibpq.o

# target to build an object file
testlibpq.c.o:
	$(MAKE) -f CMakeFiles/testlibpq.exe.dir/build.make CMakeFiles/testlibpq.exe.dir/testlibpq.c.o
.PHONY : testlibpq.c.o

testlibpq.i: testlibpq.c.i

.PHONY : testlibpq.i

# target to preprocess a source file
testlibpq.c.i:
	$(MAKE) -f CMakeFiles/testlibpq.exe.dir/build.make CMakeFiles/testlibpq.exe.dir/testlibpq.c.i
.PHONY : testlibpq.c.i

testlibpq.s: testlibpq.c.s

.PHONY : testlibpq.s

# target to generate assembly for a file
testlibpq.c.s:
	$(MAKE) -f CMakeFiles/testlibpq.exe.dir/build.make CMakeFiles/testlibpq.exe.dir/testlibpq.c.s
.PHONY : testlibpq.c.s

testlibpq2.o: testlibpq2.c.o

.PHONY : testlibpq2.o

# target to build an object file
testlibpq2.c.o:
	$(MAKE) -f CMakeFiles/testlibpq2.exe.dir/build.make CMakeFiles/testlibpq2.exe.dir/testlibpq2.c.o
.PHONY : testlibpq2.c.o

testlibpq2.i: testlibpq2.c.i

.PHONY : testlibpq2.i

# target to preprocess a source file
testlibpq2.c.i:
	$(MAKE) -f CMakeFiles/testlibpq2.exe.dir/build.make CMakeFiles/testlibpq2.exe.dir/testlibpq2.c.i
.PHONY : testlibpq2.c.i

testlibpq2.s: testlibpq2.c.s

.PHONY : testlibpq2.s

# target to generate assembly for a file
testlibpq2.c.s:
	$(MAKE) -f CMakeFiles/testlibpq2.exe.dir/build.make CMakeFiles/testlibpq2.exe.dir/testlibpq2.c.s
.PHONY : testlibpq2.c.s

testlibpq3.o: testlibpq3.c.o

.PHONY : testlibpq3.o

# target to build an object file
testlibpq3.c.o:
	$(MAKE) -f CMakeFiles/testlibpq3.exe.dir/build.make CMakeFiles/testlibpq3.exe.dir/testlibpq3.c.o
.PHONY : testlibpq3.c.o

testlibpq3.i: testlibpq3.c.i

.PHONY : testlibpq3.i

# target to preprocess a source file
testlibpq3.c.i:
	$(MAKE) -f CMakeFiles/testlibpq3.exe.dir/build.make CMakeFiles/testlibpq3.exe.dir/testlibpq3.c.i
.PHONY : testlibpq3.c.i

testlibpq3.s: testlibpq3.c.s

.PHONY : testlibpq3.s

# target to generate assembly for a file
testlibpq3.c.s:
	$(MAKE) -f CMakeFiles/testlibpq3.exe.dir/build.make CMakeFiles/testlibpq3.exe.dir/testlibpq3.c.s
.PHONY : testlibpq3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... testlibpq3.exe"
	@echo "... testlibpq2.exe"
	@echo "... testlibpq.exe"
	@echo "... edit_cache"
	@echo "... test.exe"
	@echo "... pq"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... testlibpq.o"
	@echo "... testlibpq.i"
	@echo "... testlibpq.s"
	@echo "... testlibpq2.o"
	@echo "... testlibpq2.i"
	@echo "... testlibpq2.s"
	@echo "... testlibpq3.o"
	@echo "... testlibpq3.i"
	@echo "... testlibpq3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

