#include "pg_config_linux_x64.h"

#define PG_MAJORVERSION "13"
#define PG_MAJORVERSION_NUM 13
#define PG_MINORVERSION_NUM 2
#define PG_VERSION "13.2"
#define PG_VERSION_NUM 130002
#define PG_VERSION_STR "PostgreSQL 13.2 libpq-standalone"


/* #undef LIBPQ_WITH_OPENSSL */

#ifdef LIBPQ_WITH_OPENSSL
#define USE_OPENSSL 1
#define HAVE_ASN1_STRING_GET0_DATA 1
#define HAVE_BIO_GET_DATA 1
#define HAVE_BIO_METH_NEW 1
#define HAVE_LIBCRYPTO 1
#define HAVE_LIBSSL 1
#define HAVE_OPENSSL_INIT_SSL 1
#define HAVE_SSL_CLEAR_OPTIONS 1
#define HAVE_X509_GET_SIGNATURE_NID 1
#define USE_OPENSSL_RANDOM 1
#undef USE_DEV_URANDOM
#endif
